[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
rust-version = "1.91"

[workspace.dependencies]
anyhow = "1"
arrow = "58"
async-trait = { version = "^0.1.89" }
chrono = { version = "0.4.44", features = ["serde"] }
config = "0.15.19"
datafusion = "53.1"
datafusion-common = "53.1"
datafusion-expr = "53.1"
futures = "0.3.32"
object_store = { version = "0.13.2", features = ["azure", "aws", "gcp"] }
olai-http = { version = "0.0.1" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
sqlx = { version = "0.8", default-features = false, features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
    "macros",
    "chrono",
    "json",
    "migrate",
    "uuid",
] }
thiserror = { version = "2" }
tokio = { version = "1.47", features = ["macros", "rt", "sync"] }
tracing = { version = "0.1", features = ["log"] }
url = { version = "2.5.2", features = [
    "serde",
    "std",
], default-features = false }
uuid = { version = "1", features = ["v4", "v5"] }
